config/routes.rb
Rails.application.routes.draw do
  resources :friendships, only:[:create, :destroy]
  get 'channel', to: 'channel#private_channel', as: "private_channel"
  root 'chatroom#index'
  get 'login' , to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'friends', to: 'friends#index'
  get 'search_friend', to: 'friends#search'
  post 'toggle_family', to: 'friends#toggle_family'
  post 'private_channel/:friend', to: 'messages#message_private', as: "private_message"
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    channel = between(sender_id, recipient_id).first
    return channel if channel.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  scope :family, -> { where(is_family: true) }
  scope :friend, -> { where(is_family: false) }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel, optional: true, class_name: "Channel"
  validates :body, presence: true
  scope :all_chat, -> { where(channel_id: nil).order(:created_at).last(20) }
  scope :private_last_20, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15}
  has_many :messages
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :channels, foreign_key: :sender_id
  has_secure_password

  def add_friend(friend)
    self.friends << friend
    friend.friends << self
  end

  def remove_friend(friend_id)
    friendship = get_friendship(friend_id)
    friendship.each do |f|
      f.destroy
    end
  end

  def toggle_family(friend_id)
    friendship = get_friendship(friend_id)
    friendship.each do |f|
      f.is_family = !f.is_family
      f.save
    end
  end

  def self.search(param)
    param.strip!
    to_send_back = where("username like ?", "%#{param}%").uniq
    to_send_back
  end

  def except_current_user(users)
    users.reject{ |user| user.id == self.id}
  end

  def is_family
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end

  def get_family
    family = Friendship.where(user_id: self.id).family.all
    fam = []
    family.each do |f|
      fam << User.find(f.friend_id)
    end
    fam
  end

  def get_friends
    friends = Friendship.where(user_id: self.id).friend.all
    fri = []
    friends.each do |f|
      fri << User.find(f.friend_id)
    end
    fri
  end

  def get_friendship(friend_id)
    Friendship.where(user_id: self.id, friend_id: friend_id).or(Friendship.where(user_id: friend_id, friend_id:self.id))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController

  def private_channel
    @channel = Channel.get(current_user.id, params[:friend])
    @friend = User.find(params[:friend])
    @messages = @channel.messages.private_last_20
    @message = Message.new
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.all_chat
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = current_user.get_friends
    @family = current_user.get_family
  end

  def toggle_family
    if params[:friend].present?
      friend = User.find(params[:friend])
      current_user.toggle_family(friend.id)
      flash[:success] = "Changed family status with user #{friend.username}"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to friends_path
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends.length != 0
        respond_to do |format|
          format.js { render partial: 'friends/friend_result'}
        end
      elsif @friends
        respond_to do |format|
          flash.now[:error] = "No user found with username containing #{params[:friend]}"
          format.js { render partial: 'friends/friend_result'}
        end
      end

    else
      respond_to do |format|
        flash.now[:error] = "Please enter a username to search"
        format.js { render partial: 'friends/friend_result'}
      end

    end
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    if current_user.add_friend(friend)
      if params[:user][:is_family] == "1"
        current_user.toggle_family(friend.id)
      end
      flash[:success] = "Added #{friend.username}"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to friends_path
  end

  def destroy
    current_user.remove_friend(params[:id])
    flash[:success] = "Successfully removed friend"
    redirect_to friends_path
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel_0",
                                   mod_msg: message_render(message)
    end
  end

  def message_private
    @friend = User.find(params[:friend])
    channel = Channel.get(current_user, @friend)
    message = Message.new(user_id: current_user.id, body: params[:message][:body])
    if channel.messages << message
      ActionCable.server.broadcast "chatroom_channel_#{channel.id}",
                                   mod_msg: message_render(message)
    end

  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "Error invalid login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channel/private_channel.html.erb
<%= render 'messages/chat' %>

app/views/chatroom/index.html.erb
<%= render 'messages/chat' %>

app/views/friends/_friend_result.html.erb
<%= render 'layouts/messages' %>
<% if @friends and @friends.length != 0 %>
  <div class="segment">
    <table class="ui celled table wrap-content">
      <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><strong>Name:</strong><%= friend.username %></td>
          <td class="flex"><strong>Actions:</strong>
            <% if current_user.not_friends_with?(friend) %>
              <%= form_for friend, url: friendships_path(friend: friend), method: :post do |f| %>
                <span class="mr-2">Mark as family?</span>
                <%= f.check_box :is_family, class: "ui checkbox" %>
                <%= f.submit "Add as friend", class: "mini ui button label-width"%>
              <% end %>
              <% else %>
              <label class="ui label ml-auto">You are already friends</label>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/friends/_friend_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'friends/friend_result.html' %>'

app/views/friends/_list.html.erb
<h1><%= obj == @family ? "Family members" : "Friends" %></h1>
  <table class="celled table wrap-content">
    <thead>
    <tr>
      <th>Username</th>
      <th class="wide">Actions</th>
    </tr>
    </thead>
    <tbody>
      <% obj.each do |f| %>
      <tr>
        <td class="label-width"><%= f.username %></td>
        <td>
          <div class="three ui buttons">
            <%= link_to "Remove friend", friendship_path(f), method: :delete, data: {confirm: "Are you sure?"},
                        class: "ui red button"%>
            <%= link_to obj == @family ? "Remove from family" : "Add to family",
                        toggle_family_path(friend: f), method: :post, class: "ui blue button" %>
            <%= link_to "Private chat", private_channel_path(friend: f), class: "ui grey button" %>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/friends/index.html.erb
<h1>Friends list</h1>
<h1>Search through users</h1>
<div class="ui">
  <%= form_tag search_friend_path, remote:true, method: :get do  %>
    <div class="search four column">
      <div class="ui icon input wide-element">
        <%= text_field_tag :friend, params[:friend], placeholder: "Username", class: "four column" %>
        <i class="search icon"></i>
      </div>
    </div>
  <% end %>
  <div id="results"></div>
</div>
<div class="ui grid">
  <div class="eight wide column">
    <% if @friends.count != 0 %>
      <%= render 'list', obj: @friends %>
    <% end %>
  </div>
  <div class="eight wide column">
    <% if @family.count != 0 %>
      <%= render 'list', obj:  @family %>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |msg_type, msg_content| %>
  <div class="ui <%= msg_type%> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= msg_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to :Chatroom, root_path, class: "item" %>
    <%= link_to :Friends, friends_path, class: "item" %>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
          <% else %>
            <%= link_to "Log in", login_path, class:"item" %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class:"ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_chat.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  <%= defined?(@channel) ? "You're chatting with #{@friend.username}" : "Say something" %>
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages" data-room-id="<%= defined?(@channel) ? @channel.id : 0 %>">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"},
                     url: defined?(@channel) ? private_message_path(params[:friend]) :
                            message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%= link_to "Home", root_path, class: "item" %>
          <%= link_to :Friends, friends_path, class: "item" %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>